name: Publish Release Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  reusable:
    uses: groundsgg/.github/.github/workflows/gradle-publish.yml@main
